# 다항로지스틱회귀분석
* 붓꽃의 품종 분류

In [2]:
import pandas as pd
import numpy as np
from sklearn import datasets
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

In [3]:
iris = datasets.load_iris()

In [13]:
df = pd.DataFrame(iris['data'], columns=iris['feature_names'])
df.columns = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width']
df['Target'] = iris['target']
df

sepal_length  sepal_width  petal_length  petal_width  Target
0             5.1          3.5           1.4          0.2       0
1             4.9          3.0           1.4          0.2       0
2             4.7          3.2           1.3          0.2       0
3             4.6          3.1           1.5          0.2       0
4             5.0          3.6           1.4          0.2       0
..            ...          ...           ...          ...     ...
145           6.7          3.0           5.2          2.3       2
146           6.3          2.5           5.0          1.9       2
147           6.5          3.0           5.2          2.0       2
148           6.2          3.4           5.4          2.3       2
149           5.9          3.0           5.1          1.8       2

[150 rows x 5 columns]

In [15]:
X_data = df.loc[:, 'sepal_length':'petal_width']
y_data = df.loc[:, 'Target']

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X_data, y_data, test_size = 0.2, shuffle=True, random_state=33)

print("훈련데이터 X와 y의 차원", X_train.shape, y_train.shape)
print("테스트데이터 X와 y의 차원", X_test.shape, y_test.shape)

훈련데이터 X와 y의 차원 (120, 4) (120,)
테스트데이터 X와 y의 차원 (30, 4) (30,)


In [17]:
model = LogisticRegression()
model.fit(X_train, y_train)

print("절편값:", model.intercept_)
print("회귀계수값:")
print(model.coef_)

절편값: [  9.12414779   2.52010946 -11.64425725]
회귀계수값:
[[-0.39217415  0.89114888 -2.35966834 -0.98920707]
 [ 0.43203457 -0.43230606 -0.0871321  -0.89024849]
 [-0.03986043 -0.45884282  2.44680043  1.87945556]]


In [21]:
y_test_pred = model.predict(X_test)
print("테스트데이터 실제값:", np.array(y_test))
print("테스트데이터 예측값:", y_test_pred)

테스트데이터 실제값: [1 1 0 1 2 2 0 0 2 2 2 0 2 1 2 1 2 0 1 2 0 0 2 0 2 2 1 1 2 2]
테스트데이터 예측값: [1 1 0 1 2 2 0 0 2 2 2 0 2 1 2 1 2 0 1 2 0 0 2 0 1 1 1 1 2 2]


In [22]:
accuracy = accuracy_score(y_test, y_test_pred)
print("테스트데이터 Accuracy: %.3f" % accuracy)

테스트데이터 Accuracy: 0.933


In [24]:
X_test.iloc[0,:]

sepal_length    5.7
sepal_width     2.9
petal_length    4.2
petal_width     1.3
Name: 96, dtype: float64

In [25]:
model.predict_proba([[5.2, 2.7,3.9,1.4]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  "X does not have valid feature names, but"


array([[0.04062202, 0.91074437, 0.04863361]])